INSERT INTO `USER` (`USERNAME`, `PASSWORD`) VALUES ('root','$2a$10$BEagJxXrpMrs/UZ1WXiHjubivo4OYYg56WLj08OsnEiI6ymLHtTMC');
INSERT INTO `USER` (`USERNAME`, `PASSWORD`) VALUES ('josemariasoler','$2a$10$YMRTdyRVzD4Ck11T9XMKI.rUIAykoZZYLQxFBcSQhJ6jwgFl2upiq');
INSERT INTO `USER` (`USERNAME`, `PASSWORD`) VALUES ('emmanuelolias','$2a$10$i.OWolWlfElTIAdtNQmTKuW0amd6aVYmuwvoXy8OTln3FEFob4xz.');


INSERT INTO `ROLE` (`ROLE`) VALUES ('admin');

INSERT INTO `REL_USER_ROLE` (`ID_USER`, `ID_ROLE`) VALUES (
    (SELECT ID FROM `USER` WHERE `USERNAME`='root'),
    (SELECT ID FROM `ROLE` WHERE `ROLE`='admin'));

INSERT INTO `ROLE` (`ROLE`) VALUES ('user');

INSERT INTO `REL_USER_ROLE` (`ID_USER`, `ID_ROLE`) VALUES (
    (SELECT ID FROM `USER` WHERE `USERNAME`='josemariasoler'),
    (SELECT ID FROM `ROLE` WHERE `ROLE`='user'));
INSERT INTO `REL_USER_ROLE` (`ID_USER`, `ID_ROLE`) VALUES (
    (SELECT ID FROM `USER` WHERE `USERNAME`='emmanuelolias'),
    (SELECT ID FROM `ROLE` WHERE `ROLE`='user'));