INSERT INTO `USER` (`USERNAME`, `PASSWORD`) VALUES ('root','$2a$10$BEagJxXrpMrs/UZ1WXiHjubivo4OYYg56WLj08OsnEiI6ymLHtTMC');


INSERT INTO `ROLE` (`ROLE`) VALUES ('admin');

INSERT INTO `REL_USER_ROLE` (`ID_USER`, `ID_ROLE`) VALUES (
    (SELECT ID FROM `USER` WHERE `USERNAME`='root'),
    (SELECT ID FROM `ROLE` WHERE `ROLE`='admin'));

INSERT INTO `ROLE` (`ROLE`) VALUES ('user');

INSERT INTO `REL_USER_ROLE` (`ID_USER`, `ID_ROLE`) VALUES (
    (SELECT ID FROM `USER` WHERE `USERNAME`='root'),
    (SELECT ID FROM `ROLE` WHERE `ROLE`='user'));